artifact_location: file:///C:/Users/Vetri%20GP/PT_MLFLOW_PROJECT/ml_model/mlruns/0
creation_time: 1710690266103
experiment_id: '0'
last_update_time: 1710690266103
lifecycle_stage: active
name: Default
